repos:
  # --- Python Auto-Format ---
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black

  - repo: local
    hooks:
      # --- C++ Auto-Format ---
      - id: ament_uncrustify
        name: ament_uncrustify
        entry: >
          docker exec cougars-ct bash -c
          'source /opt/ros/humble/setup.bash &&
          ament_uncrustify --reformat "$@"' --
        language: system
        files: ^coug_ws/src/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$

      # --- C++ Linting ---
      - id: ament_cpplint
        name: ament_cpplint
        entry: >
          docker exec cougars-ct bash -c
          'source /opt/ros/humble/setup.bash &&
          ament_cpplint "$@"' --
        language: system
        files: ^coug_ws/src/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$

      - id: ament_cppcheck
        name: ament_cppcheck
        entry: >
          docker exec cougars-ct bash -c
          'source /opt/ros/humble/setup.bash &&
          export AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS=1 &&
          ament_cppcheck "$@"' --
        language: system
        files: ^coug_ws/src/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$

      # --- Python Linting ---
      - id: ament_flake8
        name: ament_flake8
        entry: >
          docker exec cougars-ct bash -c
          'source /opt/ros/humble/setup.bash &&
          ament_flake8 "$@"' --
        language: system
        files: ^coug_ws/src/.*\.py$
        exclude: /setup\.py$

      - id: ament_pep257
        name: ament_pep257
        name: ament_pep257
        entry: >
          docker exec cougars-ct bash -c
          'source /opt/ros/humble/setup.bash &&
          ament_pep257 "$@"' --
        language: system
        files: ^coug_ws/src/.*\.py$
        exclude: /setup\.py$

      # --- CMake & XML Linting ---
      - id: ament_lint_cmake
        name: ament_lint_cmake
        entry: >
          docker exec cougars-ct bash -c
          'source /opt/ros/humble/setup.bash &&
          ament_lint_cmake "$@"' --
        language: system
        files: CMakeLists\.txt$

      - id: ament_xmllint
        name: ament_xmllint
        entry: >
          docker exec cougars-ct bash -c
          'source /opt/ros/humble/setup.bash &&
          ament_xmllint "$@"' --
        language: system
        files: ^coug_ws/src/.*\.xml$

      # --- Copyright Check ---
      - id: ament_copyright
        name: ament_copyright
        entry: >
          docker exec cougars-ct bash -c
          'source /opt/ros/humble/setup.bash &&
          ament_copyright "$@"' --
        language: system
        files: ^coug_ws/src/
        exclude: |
            (?x)^(
                .*\.json|
                .*\.yaml|
                .*\.yml|
                .*\.xml|
                .*\.repos|
                .*\.txt|
                .*/setup\.py
            )$
