/coug2sim/**:
  ros__parameters:
    prior:
      parameter_priors:
        initial_position: [0.0, 40.0, 0.0] # [m]

/coug2sim/ekf_filter_node_map:
  ros__parameters:
    initial_state: [0.0, 40.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]

/coug2sim/ukf_filter_node_map:
  ros__parameters:
    initial_state: [0.0, 40.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]
